# pylint: disable=invalid-name, missing-class-docstring, missing-function-docstring, missing-module-docstring, redefined-builtin, too-few-public-methods, unused-argument
from typing import Optional, Tuple

class Image:
    @staticmethod
    def new(mode: str, size: Tuple[int, int], color: Optional[int] = 0) -> "Image": ...
    def save(self, fp: str, format: Optional[str] = None) -> None: ...
    def show(self, title: Optional[str] = None) -> None: ...

class ImageFont:
    @staticmethod
    def truetype(font: str, size: int) -> "ImageFont": ...

class ImageDraw:
    @staticmethod
    def Draw(image: Image, mode: Optional[str] = None) -> "ImageDraw": ...
    def multiline_text(
        self, xy: Tuple[int, int], text: str, fill: int, font: ImageFont
    ) -> None: ...
