name: ci
on:
  push:
    branches: [trunk]
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache /.poetry
        uses: actions/cache@v3
        with:
          path: .poetry
          key: dodo-${{ hashFiles('poetry.lock') }}
      - name: Set up Python virtual environment
        run: ./py
      - name: Check
        run: ./py check
      - name: Test
        run: ./py test
